apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-svc
  labels:
    name: ingress-svc
spec:
  tls:
  - hosts:
    - app.bid-a-ride.local
    - api.bid-a-ride.local
    - id.bid-a-ride.local
    secretName: bid-a-ride-app-tls
  ingressClassName: nginx
  rules:
  - host: app.bid-a-ride.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: webapp-clusterip
            port: 
              number: 3000
  - host: api.bid-a-ride.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: gateway-clusterip
            port: 
              number: 80
  - host: id.bid-a-ride.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: identity-clusterip
            port: 
              number: 80